export const API_endpoints = {
  // auth
  loginUser: "/api/auth/login",
  registerUser: "/api/auth/register",
  // countries
  getAllCountries: "/api/countries",
  addCountry: "/api/countries",
  updateCountry: "/api/countries",
  deleteCountry: "/api/countries",
  // states
  getAllStates: "/api/states",
  addState: "/api/states",
  updateState: "/api/states",
  deleteState: "/api/states",
  // districts
  getAllDistricts: "/api/districts",
  addDistrict: "/api/districts",
  updateDistrict: "/api/districts",
  deleteDistrict: "/api/districts",
  // streams
  getAllStreams: "/api/streams",
  addStream: "/api/streams",
  updateStream: "/api/streams",
  deleteStream: "/api/streams",
  // roles
  getAllRoles: "/api/role",
  // users
  getAllUsers: "/api/user",
  addUser: "/api/user",
  updateUser: "/api/user",
  deleteUser: "/api/user",
  getUsersForRole: "/api/user/roles",
  // organisations
  getAllOrganisations: "/api/organisations",
  addOrganisation: "/api/organisations",
  updateOrganisation: "/api/organisations",
  deleteOrganisation: "/api/organisations",
  // departments
  getAllDepartments: "/api/departments",
  addDepartment: "/api/departments",
  updateDepartment: "/api/departments",
  deleteDepartment: "/api/departments",
  // universities
  getAllUniversities: "/api/universities",
  addUniversity: "/api/universities",
  updateUniversity: "/api/universities",
  deleteUniversity: "/api/universities",
  addCompetition: "/api/competition"
};
